# Generated by Django 3.2.9 on 2021-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='Products_image/')),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
